#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-microware.svhr-ecom}
VERSION=${2:-2.4.6-p2}
EDITION=${3:-community}

curl -s https://raw.githubusercontent.com/ffm-cloud/Microware-Magento/master/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
bin/download "${VERSION}" "${EDITION}" \
  && bin/setup "${DOMAIN}"